"""Project scaffolding — create the input/output contract for a new project.

A project is *data*, not code. It lives under ``~/Video/Projects/`` on the daily
driver and archives to Drive. The pipeline reads ``source/`` and never writes it;
``render/`` ships empty on purpose so future scheduling/publishing automation can
treat "file present in render/" as "deliverable ready".

    {project-id}/
      project.yml   manifest (identity, profile, rough_cut.trim_filler, metadata)
      source/       human-assembled inputs (READ-only by the pipeline)
      work/         pipeline intermediates (regenerable, disposable)
      review/       decision file, preview renders, safe-zone preview, contact sheets
      out/          editor handoff: FCPXML + rendered caption/overlay layers
      render/       FINAL exported reel (shipped EMPTY)
"""

from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path
from typing import Optional

import yaml

from .manifest import Manifest, parse_folder_name

SUBDIRS = ("source", "work", "review", "out", "render")


@dataclass(frozen=True)
class ProjectPaths:
    root: Path
    manifest: Path
    source: Path
    work: Path
    review: Path
    out: Path
    render: Path


def project_paths(project_root: str | Path) -> ProjectPaths:
    root = Path(project_root)
    return ProjectPaths(
        root=root,
        manifest=root / "project.yml",
        source=root / "source",
        work=root / "work",
        review=root / "review",
        out=root / "out",
        render=root / "render",
    )


def _manifest_yaml(manifest: Manifest, folder_name: str) -> str:
    fn = parse_folder_name(folder_name)
    data = {
        "project_id": folder_name,
        "identity": manifest.identity,
        "profile": manifest.profile,
        "rough_cut": {"trim_filler": manifest.trim_filler},
        "metadata": {
            "date": fn.date,
            "hook": fn.hook,
            "render_filename": fn.render_filename(),
            **(manifest.metadata or {}),
        },
    }
    header = (
        "# project.yml — generated by video_pipeline.project.create_project\n"
        "# identity -> config/glossary layer; profile -> dimensions + safe-zone spec.\n"
        "# source/ is never modified by the pipeline; render/ is filled by the editor.\n"
    )
    return header + yaml.safe_dump(data, sort_keys=False, allow_unicode=True)


def create_project(
    projects_root: str | Path,
    folder_name: str,
    identity: str,
    profile: str,
    trim_filler: bool = True,
    exist_ok: bool = False,
) -> ProjectPaths:
    """Create ``{projects_root}/{folder_name}/`` with the standard layout.

    ``folder_name`` must follow 'YYYY-MM-DD <Token> Project - <Hook>'. Returns
    the resolved ProjectPaths. ``source/`` and ``render/`` are created empty.
    """
    parse_folder_name(folder_name)  # validate the convention up front

    root = Path(projects_root) / folder_name
    if root.exists() and not exist_ok:
        raise FileExistsError(f"project already exists: {root}")

    paths = project_paths(root)
    root.mkdir(parents=True, exist_ok=exist_ok)
    for sub in SUBDIRS:
        (root / sub).mkdir(exist_ok=True)

    manifest = Manifest(identity=identity, profile=profile, trim_filler=trim_filler)
    paths.manifest.write_text(_manifest_yaml(manifest, folder_name), encoding="utf-8")
    return paths
