"""The decision file — the product of the rough-cut phase.

The edit-decision file *is the deliverable*; the rough render is a regenerable
view of it. It is a human-editable YAML document: a flat, ordered list of
segments that partition the source clip end-to-end. Each segment is KEEP or
DROP. The rough cut is the concatenation of the KEEP segments, in order.

To edit the cut, the CEO flips ``keep:`` on a segment (or nudges ``start`` /
``end``) and re-renders. The edit round-trips: ``DecisionList.from_yaml`` parses
exactly what ``to_yaml`` writes, so a hand-edited file loads back losslessly.
The pipeline never modifies ``source/``; the decision file lives in ``review/``
and the rough render in ``work/``.

Example (abridged)::

    source: 2026-06-03-reel.mp4
    profile: reels-9x16
    trim_filler: true
    segments:
      - {i: 0, start: 0.000, end: 0.400, keep: false, reason: silence,     text: ""}
      - {i: 1, start: 0.400, end: 3.120, keep: true,  reason: "",          text: "Hey what's up"}
      - {i: 2, start: 3.120, end: 3.460, keep: false, reason: filler,      text: "um"}
"""

from __future__ import annotations

from dataclasses import dataclass, field
from typing import List, Optional

import yaml


def _round(t: float) -> float:
    return round(float(t), 3)


@dataclass
class Segment:
    """One contiguous span of the source clip.

    ``keep`` True => the span is in the rough cut. ``reason`` explains a DROP
    ('filler' | 'false-start' | 'silence' | 'manual'); it is "" for kept
    content. ``text`` is the transcript inside the span (for the human reading
    the file). ``index`` is positional and purely cosmetic.
    """

    index: int
    start: float
    end: float
    keep: bool
    reason: str = ""
    text: str = ""

    def __post_init__(self):
        self.start = _round(self.start)
        self.end = _round(self.end)

    @property
    def duration(self) -> float:
        return _round(max(0.0, self.end - self.start))

    def to_dict(self) -> dict:
        # compact, key-ordered mapping (renders inline as flow style)
        return {
            "i": self.index,
            "start": self.start,
            "end": self.end,
            "keep": self.keep,
            "reason": self.reason,
            "text": self.text,
        }

    @classmethod
    def from_dict(cls, d: dict) -> "Segment":
        return cls(
            index=int(d.get("i", d.get("index", 0))),
            start=float(d["start"]),
            end=float(d["end"]),
            keep=bool(d["keep"]),
            reason=str(d.get("reason", "") or ""),
            text=str(d.get("text", "") or ""),
        )


_HEADER = (
    "# decision file — generated by video_pipeline.roughcut (INI-085 Phase 2).\n"
    "# THIS FILE IS THE PRODUCT. The rough cut is a regenerable render of it.\n"
    "# Edit the cut by flipping `keep:` on a segment (or nudging start/end), then\n"
    "# re-render:  video-pipeline roughcut-render <this-file> -i <source> -o <out.mp4>\n"
    "# `reason` is advisory (filler | false-start | silence | manual). source/ is\n"
    "# never modified — only KEEP segments, in order, appear in the rough cut.\n"
)


@dataclass
class DecisionList:
    """An ordered decision document over a single source clip."""

    source: str
    segments: List[Segment] = field(default_factory=list)
    profile: Optional[str] = None
    trim_filler: bool = True
    duration: Optional[float] = None

    # ── views ────────────────────────────────────────────────────────────────

    def kept(self) -> List[Segment]:
        return [s for s in self.segments if s.keep]

    def kept_duration(self) -> float:
        return _round(sum(s.duration for s in self.kept()))

    def source_duration(self) -> float:
        if self.duration is not None:
            return _round(self.duration)
        return _round(self.segments[-1].end if self.segments else 0.0)

    def reindex(self) -> "DecisionList":
        """Renumber segments 0..n-1 in time order (after a hand edit)."""
        self.segments.sort(key=lambda s: (s.start, s.end))
        for i, s in enumerate(self.segments):
            s.index = i
        return self

    # ── serialization ──────────────────────────────────────────────────────────

    def to_yaml(self) -> str:
        head = {
            "source": self.source,
            "profile": self.profile,
            "trim_filler": self.trim_filler,
            "duration": _round(self.source_duration()),
            "kept_duration": self.kept_duration(),
        }
        head_yaml = yaml.safe_dump(
            head, sort_keys=False, allow_unicode=True, default_flow_style=False
        )
        # Segments render one-per-line in flow style ({i: 0, start: ...}) so the
        # decision file reads like a script and a keep-flip is a single-line edit.
        lines = ["segments:"]
        for s in self.segments:
            row = yaml.safe_dump(
                s.to_dict(), sort_keys=False, allow_unicode=True,
                default_flow_style=True, width=10_000,
            ).strip()
            lines.append(f"  - {row}")
        return _HEADER + head_yaml + "\n".join(lines) + "\n"

    @classmethod
    def from_yaml(cls, text: str) -> "DecisionList":
        data = yaml.safe_load(text) or {}
        if not isinstance(data, dict):
            raise ValueError("decision file did not parse to a mapping")
        segments = [Segment.from_dict(d) for d in (data.get("segments") or [])]
        return cls(
            source=str(data.get("source", "")),
            segments=segments,
            profile=data.get("profile"),
            trim_filler=bool(data.get("trim_filler", True)),
            duration=(float(data["duration"]) if data.get("duration") is not None else None),
        )

    def write(self, path) -> None:
        from pathlib import Path

        Path(path).write_text(self.to_yaml(), encoding="utf-8")

    @classmethod
    def read(cls, path) -> "DecisionList":
        from pathlib import Path

        return cls.from_yaml(Path(path).read_text(encoding="utf-8"))
